import type { NextPage } from "next";
import { useSession, signIn, signOut } from "next-auth/react";

import Head from "next/head";
import { useEffect, useState } from "react";

import dynamic from "next/dynamic";
import Router from "next/router";
import Link from "next/link";

// const Video = dynamic(import("../components/Video"), { ssr: false });

const Home: NextPage = () => {
  const session = useSession();

  useEffect(() => {
    //Redirect the user to the login page
    if (session.status == "unauthenticated") {
      Router.push("/login");
    }
  }, [session]);

  if (session.status == "loading")
    return (
      <div className="w-full h-screen flex justify-center items-center">
        <p className="btn loading">Loading</p>
      </div>
    );

  // console.log(session);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {session.data && (
        <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
          <div className="card w-96 bg-base-300 p-4 space-y-6">
            <div className=" p-3 rounded-lg">
              <div className="flex avatar items-center justify-center">
                <div className="w-12 rounded-full mr-3">
                  <img src={session.data.user?.image || ""} />
                </div>
                <h2>{session.data?.user?.name}</h2>
              </div>
            </div>
            <div className="card-body items-center p-0 space-y-6">
              <h2 className="card-title text-center capitalize">
                Welcome to the next generation meeting app
              </h2>
              <div className="card-actions space-y-4">
                <div className="w-full">
                  <button className={`btn btn-primary w-full`}>
                    <Link href="/prepare">Start New Meeting</Link>
                  </button>
                </div>
                <input
                  className="input"
                  placeholder="Enter Room ID"
                  type="text"
                  name="roomID"
                  id="roomID"
                />
                <button className={`btn btn-secondary `}>Join Meeting</button>
              </div>
            </div>
          </div>
        </main>
      )}
    </>
  );
};

export default Home;
