import type { NextPage } from "next";
import { useSession } from "next-auth/react";

import Head from "next/head";
import { useEffect } from "react";

import Router from "next/router";
import JoinMeeting from "../components/JoinMeeting";
import axios from "axios";
import Navbar from "../components/Navbar";

// const Video = dynamic(import("../components/Video"), { ssr: false });

const Home: NextPage = () => {
  const session = useSession();

  useEffect(() => {
    //Redirect the user to the login page
    if (session.status == "unauthenticated") {
      Router.push("/login");
    }
  }, [session]);

  if (session.status == "loading")
    return (
      <div className="w-full h-screen flex justify-center items-center">
        <p className="btn loading">Loading</p>
      </div>
    );

  // console.log(session);
  const createNewMeeting = async () => {
    if (session.data) {
      const { data } = await axios.post("/api/room/meeting", {
        host: session.data.user?.id,
      });

      Router.push(`/prepare?id=${data.id}`);
    }
  };

  return (
    <>
      <Head>
        <title>HyperMeet</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      {session.data && (
        <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
          <div className="card w-96 bg-base-300 p-4 space-y-6">
            <div className=" p-3 rounded-lg">
              <div className="flex avatar items-center justify-center">
                <div className="w-12 rounded-full mr-3">
                  <img src={session.data.user?.image || ""} />
                </div>
                <h2>{session.data?.user?.name}</h2>
              </div>
            </div>
            <div className="card-body items-center p-0 space-y-6">
              <h2 className="card-title text-center capitalize">
                Welcome to the next generation meeting app
              </h2>
              <div className="card-actions space-y-4">
                <div className="w-full">
                  <button
                    className={`btn btn-primary w-full`}
                    onClick={createNewMeeting}
                  >
                    Start New Meeting
                  </button>
                </div>
                <JoinMeeting />
              </div>
            </div>
          </div>
        </main>
      )}
    </>
  );
};

export default Home;
