import type { NextPage } from "next";
import { useSession, signIn, signOut } from "next-auth/react";
import Head from "next/head";

const Home: NextPage = () => {
  const session = useSession();

  if (session.status == "loading")
    return (
      <div className="">
        <h3>loading...</h3>
      </div>
    );

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
        <h1 className="text-5xl md:text-[5rem] leading-normal font-extrabold text-gray-700">
          Create <span className="text-purple-300">T3</span> App
        </h1>

        {session.status == "authenticated" && (
          <div className="text-center">
            <div className="">
              <img
                className="rouned-full w-36 h-36"
                src={session.data.user?.image || ""}
                alt="user image"
              />
              <h2>{session.data.user?.name}</h2>
            </div>
            <button
              className="bg-purple-500 text-white font-bold rounded-md px-4 py-2"
              onClick={() => signOut()}
            >
              Log Out
            </button>
          </div>
        )}
        {session.status == "unauthenticated" && (
          <div className="">
            <button
              className="bg-purple-500 text-white font-bold rounded-md px-4 py-2"
              onClick={() => signIn()}
            >
              Continue With Github
            </button>
          </div>
        )}
      </main>
    </>
  );
};

export default Home;
