import { NextPage } from "next";
import React, { useEffect, useState } from "react";
import { useSession, signIn } from "next-auth/react";
import Head from "next/head";
import Router from "next/router";
import Navbar from "../components/Navbar";
const Login: NextPage = () => {
  const session = useSession();
  useEffect(() => {
    if (session.status == "authenticated") {
      Router.push("/");
    }
  });

  const [signing, setSigning] = useState(false);

  const handleSignIn = () => {
    setSigning(true);
    signIn();
  };

  return (
    <>
      <Head>
        <title>HyperMeet</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="p-3">
        <Navbar />
        <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
          <div className="card w-full max-w-sm bg-base-300">
            <div className="card-body items-center">
              <h2 className="card-title text-center capitalize text-lg">
                Welcome to the next generation meeting app
              </h2>
              <div className="card-actions">
                <button
                  className={`btn btn-primary ${signing ? "loading" : ""}`}
                  onClick={handleSignIn}
                >
                  Sign In
                </button>
              </div>
            </div>
          </div>
        </main>
      </div>
    </>
  );
};

export default Login;
