import Head from "next/head";
import Link from "next/link";
import React, { useState } from "react";
import {
  FiArrowLeft,
  FiMic,
  FiMicOff,
  FiVideo,
  FiVideoOff,
} from "react-icons/fi";
import useAuth from "../hooks/useAuth";
const PrePare = () => {
  const [isAudioActive, setIsAudioActive] = useState(true);
  const [isVideoActive, setIsVideoActive] = useState(true);
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
        <div className="card w-full max-w-md bg-base-300 space-y-3 p-4">
          <div className="card-body p-0">
            <div className="flex justify-start">
              <button className="mr-3 cursor-pointer">
                <FiArrowLeft />
              </button>
              <h2 className="card-title text-md">
                Setup Your Camera and Microphone
              </h2>
            </div>
          </div>
          <div className="card-body p-0 rounded-lg overflow-hidden">
            <img
              className="w-full h-80 object-cover"
              src="https://api.lorem.space/image/face?w=720&h=480"
              alt="Shoes"
            />
          </div>
          <div className="card-actions flex justify-center items-center">
            <button
              className="btn btn-circle text-lg"
              onClick={() => setIsAudioActive(!isAudioActive)}
            >
              {isAudioActive ? (
                <FiMic className="text-blue-500" />
              ) : (
                <FiMicOff className="text-red-500" />
              )}
            </button>
            <button
              className="btn btn-circle text-lg"
              onClick={() => setIsVideoActive(!isVideoActive)}
            >
              {isVideoActive ? (
                <FiVideo className="text-blue-500" />
              ) : (
                <FiVideoOff className="text-red-500" />
              )}
            </button>
          </div>
          <div className="card-actions flex justify-center items-center">
            <button className="btn btn-primary  w-full">
              <Link
                href={`/meeting/${Math.round(Math.random() * 10000000000000)}`}
              >
                <a className="flex justify-center items-center">
                  <FiVideo className="text-lg mr-2" /> Start New Meeting
                </a>
              </Link>
            </button>
          </div>
        </div>
      </main>
    </>
  );
};

export default PrePare;
