import { NextPage } from "next";
import Head from "next/head";
import React from "react";
import MainScreen from "../../components/MainScreen";
import Member from "../../components/Member";

const MeetingRoom: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="grid grid-cols-12 gap-6 p-4 max-w-screen-2xl fixed">
        <div className="bg-base-300 rounded-lg col-span-3 h-screen p-3 space-y-4 overflow-y-auto">
          <Member />
          <Member />
        </div>
        <div className="bg-base-300 rounded-lg col-span-6  p-4">
          <MainScreen />
        </div>
        <div className="bg-base-300 rounded-lg col-span-3 h-screen"></div>
      </main>
    </>
  );
};

export default MeetingRoom;
