import { NextPage, GetStaticProps } from "next";
import dynamic from "next/dynamic";
import Head from "next/head";
const AgoraMain = dynamic(import("../../components/AgoraMain"), { ssr: false });

type Room = {
  id: string;
  hostID: string;
};

export async function getStaticPaths() {
  const result = await fetch("http://localhost:3000/api/room");
  const data = await result.json();
  const paths = await data.map((room: Room) => {
    return { params: { roomID: room.id.toString() } };
  });
  return {
    paths,
    fallback: false,
  };
}

type Props = {
  roomInfo: {
    id: string;
    hostID: string;
  };
};

export const getStaticProps: GetStaticProps = async ({ params }) => {
  if (!params) return { props: {} };
  const result = await fetch(`http://localhost:3000/api/room/${params.roomID}`);
  const roomInfo = await result.json();
  return {
    props: {
      roomInfo,
    },
  };
};

const MeetingRoom: NextPage<Props> = ({ roomInfo }: Props) => {
  // console.log(props);
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AgoraMain />
    </>
  );
};

export default MeetingRoom;
