import { useAtom } from "jotai";
import { NextPage, GetStaticProps } from "next";
import { useSession } from "next-auth/react";
import dynamic from "next/dynamic";
import Head from "next/head";
import Router from "next/router";
import { useEffect } from "react";
import Navbar from "../../components/Navbar";
import { copyAlertAtom } from "../../jotai";
const AgoraMain = dynamic(import("../../components/AgoraMain"), { ssr: false });

const MeetingRoom: NextPage = () => {
  const session = useSession();
  const [copyAlert, setCopyAlert] = useAtom(copyAlertAtom);

  useEffect(() => {
    //Redirect the user to the login page
    if (session.status == "unauthenticated") {
      Router.push("/login");
    }
  }, [session]);

  if (session.status == "loading")
    return (
      <div className="w-full h-screen flex justify-center items-center">
        <p className="btn loading">Loading</p>
      </div>
    );

  return (
    <>
      <Head>
        <title>HyperMeet</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="p-3 relative">
        {copyAlert && (
          <div className="absolute left-1/2 right-1/2 top-5 -translate-x-1/2  alert w-full max-w-sm z-50 alert-success shadow-lg">
            <div>
              <svg
                xmlns="http://www.w3.org/2000/svg"
                className="stroke-current flex-shrink-0 h-6 w-6"
                fill="none"
                viewBox="0 0 24 24"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth="2"
                  d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"
                />
              </svg>
              <span>Meeting Link copied!</span>
            </div>
          </div>
        )}
        <Navbar />
        <AgoraMain />
      </div>
    </>
  );
};

export default MeetingRoom;
